import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { konceptdata } from "./data";

import { UserProvider } from "@/components/MyContexts";
import ReadUserSessionStorge from "@/components/ReadUserSessionStorage";
import Footer from "@/components/Footer";
import Loading from "./loading";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <meta name="robots" content="noindex,nofollow" />
        <ReadUserSessionStorge>
          <div className="breaker"></div>
          <Navbar koncepter={konceptdata} />
          {children}
          <Footer koncepter={konceptdata} />
        </ReadUserSessionStorge>
      </html>
    </UserProvider>
  );
}
