import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { UserProvider } from "@/components/MyContexts";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
